// <auto-generated />
namespace MvcGroupApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Ilk_migration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Ilk_migration));
        
        string IMigrationMetadata.Id
        {
            get { return "201905242210084_Ilk_migration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
